// <auto-generated />
using Dp.Lll.Infrastrucutre.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularWebApi.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AngularWebApi.Model.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"), 1L, 1);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AngularWebApi.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Chennai",
                            EmailId = "gajendran@gmail.com",
                            Password = "Test@123$",
                            PhoneNumber = "8956231478",
                            UserName = "Gajendran"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Coimbator",
                            EmailId = "gobi@gmail.com",
                            Password = "Test@123$",
                            PhoneNumber = "7894561237",
                            UserName = "Gobi"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Thirvanmiur",
                            EmailId = "vijey@gmail.com",
                            Password = "Test@123$",
                            PhoneNumber = "4567892589",
                            UserName = "vijeykumar"
                        },
                        new
                        {
                            UserId = 4,
                            Address = "Vadapalani",
                            EmailId = "rahul@gmail.com",
                            Password = "Test@123$",
                            PhoneNumber = "9856237415",
                            UserName = "Rahul"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
